### ISSUE TITLE
Installing this plugin via Plugin Directory fails in Docker Image

### ISSUE THREAD

**Issue by carbo18** [BlueTeck/kanboard_plugin_coverimage#13]
When trying to install this plugin in the official kanboard docker image I get an:

`Internal Error: Unable to load this plugin class \Kanboard\Plugin\Model\Plugin`

This occurs with build v1.0.34 and latest.

**Comment by TimoStahl** [comment]
I will look into it, I didn't test it with 1.0.34

**Comment by TimoStahl** [comment]
I can't reproduce you error, are there any other plugins installed?

**Comment by juanluisbaptiste** [comment]
Hi,

I think I'm having the same issue, on a clean docker installation, after clicking on the install link on the plugin directory it loads the installed plugins page but coverimage isn't listed, and if you go back to the plugin directory, the plugin is still available for install. No errors shown on the interface or in the container logs.

**Comment by TimoStahl** [comment]
I will check again, after my vacation.

**Comment by juanluisbaptiste** [comment]
Thanks !

**Comment by almereyda** [comment]
Eventually this is due to the way the extraction of this archive works.

When I install this with

    docker-compose -f compose.alpine.postgres.rabbitmq.yaml run --rm --entrypoint /var/www/app/cli app plugin:install https://github.com/BlueTeck/kanboard_plugin_coverimage/releases/download/1.0.38.0/Coverimage.zip

into the setup from https://github.com/kanboard/docker/compare/master...allmende:master it extracts all files into the plugins folder, instead of its own `Coverimage` subfolder, as all proper plugins do for themselvers with their names. I guess some refactoring for the release zip will do?
